### ISSUE TITLE
Demo "Cannot read property 'numberOfItems' of undefined"

### ISSUE THREAD

**Issue by adamlwgriffiths** [otm/svg.path.js#13]
The demo is exhibiting this issue.
`svg.js:667 Uncaught TypeError: Cannot read property 'numberOfItems' of undefined`

**Comment by otm** [comment]
Without looking at the problem I would guess that it's svg.js version that needs to be bumped.

**Comment by adamlwgriffiths** [comment]
Sorry, I meant to say that this is occuring on the [demo site](https://otm.github.io/svg.path.js/)

**Comment by otm** [comment]
Thanks for clarifying, I'll take a look at it.

**Comment by otm** [comment]
Bumped svgjs to 1.0.1

Thanks for reporting the bug

**Comment by otm** [comment]
Fixed in d45d88bb7dea6d39d78ad7a4cadb69a5fad03cc3
