### ISSUE TITLE
animation finished callback

### ISSUE THREAD

**Issue by fotock** [otm/svg.path.js#19]
Code
```javascript
var draw = SVG('line-path1').size(1200, 500);
draw.path().attr({ fill: 'none', stroke: '#fff', 'stroke-width': 2, })
.M(x1, y1).Q( {x:x1-40, y:y1-10},{x:x1-80, y:y1+80}).T({x:x1-350, y:y1+80})
.drawAnimated({ delay: 200 });
```

How could I add a callback function when drawAnimated() is finished like:
```javascript
.drawAnimated({ delay: 200 }).then(function(){
  //
});
```

Thanks.

**Comment by otm** [comment]
svg.path.js is just an extension to SVG.Path. 

I think `.after()`and `afterAll()` is what you are looking for, see http://svgjs.com/animating/#after-afterall
